In [26]:
import numpy as np
import open3d as o3d
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [27]:
pcd = o3d.io.read_point_cloud("record_00348.pcd")
print(pcd)
data =np.asarray(pcd.points)
print(data, data.shape)

geometry::PointCloud with 271983 points.
[[-0.44703168 -0.30711567  0.79800004]
 [-0.44451565 -0.30634597  0.79600006]
 [-0.44312003 -0.30634597  0.79600006]
 ...
 [ 0.24811688  0.22288465  0.53300005]
 [ 0.24905139  0.22288465  0.53300005]
 [ 0.24998593  0.22288465  0.53300005]] (271983, 3)


In [28]:
def Find_Plane(p1, p2, p3):
    
    x1 , y1, z1= p2[0]- p1[0], p2[1]- p1[1], p2[2]- p1[2]
    
    x2 , y2, z2= p2[0]- p3[0], p2[1]- p3[1], p2[2]- p3[2]
    
    b = (x1*y2 - x2*y1)/(z1*y2- z2*y1)
    
    a = (x1 - b*z1)/y1
    
    c = p1[0]-a*p1[1]-b*p1[2]
    
    return a, b, c

def Check(data, a, b, c, thre):
    
    count = 0
    
    for point in data:
        
        if np.abs(point[0]-a*point[1]-b*point[2]-c)< thre:
            
            count=count+1
            
    return count

def Draw(data, a, b, c, thre):
    
    Ps = []
    for point in data:
        
        if np.abs(point[0]-a*point[1]-b*point[2]-c)< thre:
            
            Ps.append(point)
            
    return np.array(Ps)

In [31]:
N , s , thre = 10, 3, 1e-1

num = -1
for i in range(N):
    
    np.random.shuffle(data)
    a, b, c = Find_Plane(data[0], data[1], data[2])
    
    num_cur = Check(data, a, b, c, thre)
    
    if num_cur > num:
        
        num = num_cur
        
        Points = [a, b, c]
        
print(num)
print(Points)

222303
[-7.639110826366834, -5.614288585794924, 4.962794045016753]


In [34]:
Ps = Draw(data, Points[0], Points[1], Points[2], thre)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(Ps)
o3d.visualization.draw_geometries([pcd])